/* USERS */
export const GET_RESIDENT_INFO_INITIAL = 'GET_RESIDENT_INFO_INITIAL'
export const GET_RESIDENT_INFO_FAIL = 'GET_RESIDENT_INFO_FAIL'
export const GET_RESIDENT_INFO_SUCCESS = 'GET_RESIDENT_INFO_SUCCESS'

