/* USERS */
export const GET_PLANET_INFO_INITIAL = 'GET_PLANET_INFO_INITIAL'
export const GET_PLANET_INFO_FAIL = 'GET_PLANET_INFO_FAIL'
export const GET_PLANET_INFO_SUCCESS = 'GET_PLANET_INFO_SUCCESS'




