/* USERS */
export const GET_PLANET_LIST_INITIAL = 'GET_PLANET_LIST_INITIAL'
export const GET_PLANET_LIST_FAIL = 'GET_PLANET_LIST_FAIL'
export const GET_PLANET_LIST_SUCCESS = 'GET_PLANET_LIST_SUCCESS'




